from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Comment(object):
    def setupUi(self, Comment):
        Comment.setObjectName("Comment")
        Comment.resize(600, 600)
        self.scrollArea = QtWidgets.QScrollArea(Comment)
        self.scrollArea.setGeometry(QtCore.QRect(39, 40, 501, 411))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 499, 409))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(20, 10, 461, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textBrowser_see_comment = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_see_comment.setGeometry(QtCore.QRect(10, 10, 351, 111))
        self.textBrowser_see_comment.setObjectName("textBrowser_see_comment")
        self.Like_button = QtWidgets.QCheckBox(self.frame)
        self.Like_button.setGeometry(QtCore.QRect(370, 100, 70, 17))
        self.Like_button.setObjectName("Like_button")
        self.Reply_button = QtWidgets.QPushButton(self.frame)
        self.Reply_button.setGeometry(QtCore.QRect(370, 70, 75, 23))
        self.Reply_button.setObjectName("Reply_button")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(370, 10, 71, 16))
        self.label.setObjectName("label")
        self.username = QtWidgets.QLabel(self.frame)
        self.username.setGeometry(QtCore.QRect(370, 30, 81, 20))
        self.username.setObjectName("username")
        self.SeeProfile_button = QtWidgets.QPushButton(self.frame)
        self.SeeProfile_button.setGeometry(QtCore.QRect(370, 50, 75, 23))
        self.SeeProfile_button.setObjectName("SeeProfile_button")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Send_button = QtWidgets.QPushButton(Comment)
        self.Send_button.setGeometry(QtCore.QRect(380, 500, 75, 23))
        self.Send_button.setObjectName("Send_button")
        self.Back_button = QtWidgets.QCommandLinkButton(Comment)
        self.Back_button.setGeometry(QtCore.QRect(380, 530, 185, 41))
        self.Back_button.setObjectName("Back_button")
        self.textEdit_Write_your_comment = QtWidgets.QTextEdit(Comment)
        self.textEdit_Write_your_comment.setGeometry(QtCore.QRect(43, 480, 311, 101))
        self.textEdit_Write_your_comment.setObjectName("textEdit_Write_your_comment")

        self.retranslateUi(Comment)
        QtCore.QMetaObject.connectSlotsByName(Comment)

    def retranslateUi(self, Comment):
        _translate = QtCore.QCoreApplication.translate
        Comment.setWindowTitle(_translate("Comment", "Form"))
        self.Like_button.setText(_translate("Comment", "like"))
        self.Reply_button.setText(_translate("Comment", "Reply"))
        self.label.setText(_translate("Comment", "UserName:"))
        self.username.setText(_translate("Comment", "User_"))
        self.SeeProfile_button.setText(_translate("Comment", "SeeProfile"))
        self.Send_button.setText(_translate("Comment", "send"))
        self.Back_button.setText(_translate("Comment", "Back"))


ui = Ui_Comment()
