from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditProfile(object):
    def setupUi(self, EditProfile):
        EditProfile.setObjectName("EditProfile")
        EditProfile.resize(600, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditProfile)
        self.verticalLayout.setObjectName("verticalLayout")
        self.firstName = QtWidgets.QLabel(EditProfile)
        self.firstName.setObjectName("firstName")
        self.verticalLayout.addWidget(self.firstName)
        self.lineEdit_firstName = QtWidgets.QLineEdit(EditProfile)
        self.lineEdit_firstName.setObjectName("lineEdit_firstName")
        self.verticalLayout.addWidget(self.lineEdit_firstName)
        self.lastName = QtWidgets.QLabel(EditProfile)
        self.lastName.setObjectName("lastName")
        self.verticalLayout.addWidget(self.lastName)
        self.lineEdit_lastName = QtWidgets.QLineEdit(EditProfile)
        self.lineEdit_lastName.setObjectName("lineEdit_lastName")
        self.verticalLayout.addWidget(self.lineEdit_lastName)
        self.intro = QtWidgets.QLabel(EditProfile)
        self.intro.setObjectName("intro")
        self.verticalLayout.addWidget(self.intro)
        self.lineEdit_intro = QtWidgets.QLineEdit(EditProfile)
        self.lineEdit_intro.setObjectName("lineEdit_intro")
        self.verticalLayout.addWidget(self.lineEdit_intro)
        self.birthday = QtWidgets.QLabel(EditProfile)
        self.birthday.setObjectName("birthday")
        self.verticalLayout.addWidget(self.birthday)
        self.dateEdit_birthday = QtWidgets.QDateEdit(EditProfile)
        self.dateEdit_birthday.setObjectName("dateEdit_birthday")
        self.verticalLayout.addWidget(self.dateEdit_birthday)
        self.username = QtWidgets.QLabel(EditProfile)
        self.username.setObjectName("username")
        self.verticalLayout.addWidget(self.username)
        self.lineEdit_username = QtWidgets.QLineEdit(EditProfile)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout.addWidget(self.lineEdit_username)
        self.password = QtWidgets.QLabel(EditProfile)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.lineEdit_password = QtWidgets.QLineEdit(EditProfile)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout.addWidget(self.lineEdit_password)
        self.email = QtWidgets.QLabel(EditProfile)
        self.email.setObjectName("email")
        self.verticalLayout.addWidget(self.email)
        self.lineEdit_email = QtWidgets.QLineEdit(EditProfile)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.verticalLayout.addWidget(self.lineEdit_email)
        self.address = QtWidgets.QLabel(EditProfile)
        self.address.setObjectName("address")
        self.verticalLayout.addWidget(self.address)
        self.lineEdit_address = QtWidgets.QLineEdit(EditProfile)
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.verticalLayout.addWidget(self.lineEdit_address)
        self.telNum = QtWidgets.QLabel(EditProfile)
        self.telNum.setObjectName("telNum")
        self.verticalLayout.addWidget(self.telNum)
        self.lineEdit_telNum = QtWidgets.QLineEdit(EditProfile)
        self.lineEdit_telNum.setObjectName("lineEdit_telNum")
        self.verticalLayout.addWidget(self.lineEdit_telNum)
        self.back_button = QtWidgets.QPushButton(EditProfile)
        self.back_button.setObjectName("back_button")
        self.verticalLayout.addWidget(self.back_button)
        self.submit_button = QtWidgets.QPushButton(EditProfile)
        self.submit_button.setObjectName("submit_button")
        self.verticalLayout.addWidget(self.submit_button)

        self.retranslateUi(EditProfile)
        QtCore.QMetaObject.connectSlotsByName(EditProfile)

    def retranslateUi(self, EditProfile):
        _translate = QtCore.QCoreApplication.translate
        EditProfile.setWindowTitle(_translate("EditProfile", "Form"))
        self.firstName.setText(_translate("EditProfile", "first name"))
        self.lastName.setText(_translate("EditProfile", "last name"))
        self.intro.setText(_translate("EditProfile", "intro"))
        self.birthday.setText(_translate("EditProfile", "birthday"))
        self.username.setText(_translate("EditProfile", "username"))
        self.password.setText(_translate("EditProfile", "password"))
        self.email.setText(_translate("EditProfile", "email"))
        self.address.setText(_translate("EditProfile", "address"))
        self.telNum.setText(_translate("EditProfile", "tel num"))
        self.back_button.setText(_translate("EditProfile", "Back"))
        self.submit_button.setText(_translate("EditProfile", "Submit"))


ui = Ui_EditProfile()
