from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_firstName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_firstName.setGeometry(QtCore.QRect(10, 69, 582, 25))
        self.lineEdit_firstName.setObjectName("lineEdit_firstName")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 198, 582, 60))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 295, 582, 61))
        self.label_4.setObjectName("label_4")
        self.back_Button = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.back_Button.setGeometry(QtCore.QRect(10, 523, 582, 61))
        self.back_Button.setObjectName("back_Button")
        self.lineEdit_emailAdd = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_emailAdd.setGeometry(QtCore.QRect(10, 362, 582, 25))
        self.lineEdit_emailAdd.setObjectName("lineEdit_emailAdd")
        self.lineEdit_telNum = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_telNum.setGeometry(QtCore.QRect(10, 264, 582, 25))
        self.lineEdit_telNum.setObjectName("lineEdit_telNum")
        self.next_Button = QtWidgets.QPushButton(self.centralwidget)
        self.next_Button.setGeometry(QtCore.QRect(10, 492, 582, 25))
        self.next_Button.setObjectName("next_Button")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 393, 582, 61))
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 582, 61))
        self.label_2.setObjectName("label_2")
        self.lineEdit_lastName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_lastName.setGeometry(QtCore.QRect(10, 167, 582, 25))
        self.lineEdit_lastName.setObjectName("lineEdit_lastName")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 2, 582, 61))
        self.label.setObjectName("label")
        self.dateEdit_birthday = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_birthday.setGeometry(QtCore.QRect(10, 460, 582, 26))
        self.dateEdit_birthday.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateEdit_birthday.setKeyboardTracking(True)
        self.dateEdit_birthday.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_birthday.setObjectName("dateEdit_birthday")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Telephone number :"))
        self.label_4.setText(_translate("MainWindow", "Email Address:"))
        self.back_Button.setText(_translate("MainWindow", "Back"))
        self.next_Button.setText(_translate("MainWindow", "Next"))
        self.label_6.setText(_translate("MainWindow", "Birthday:"))
        self.label_2.setText(_translate("MainWindow", "Last name :"))
        self.label.setText(_translate("MainWindow", "First name :"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())

ui = Ui_MainWindow()
