# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from .home import ui as ui_home

class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(600, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.UserName_libale = QtWidgets.QLabel(Login)
        self.UserName_libale.setObjectName("UserName_libale")
        self.verticalLayout.addWidget(self.UserName_libale)
        self.UserName_lineEdit = QtWidgets.QLineEdit(Login)
        self.UserName_lineEdit.setObjectName("UserName_lineEdit")
        self.verticalLayout.addWidget(self.UserName_lineEdit)
        self.label_3 = QtWidgets.QLabel(Login)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.Password_lineEdit = QtWidgets.QLineEdit(Login)
        self.Password_lineEdit.setObjectName("Password_lineEdit")
        self.verticalLayout.addWidget(self.Password_lineEdit)
        self.LoginButton = QtWidgets.QPushButton(Login)
        self.LoginButton.setObjectName("LoginButton")
        self.verticalLayout.addWidget(self.LoginButton)
        self.SingUpButton = QtWidgets.QPushButton(Login)
        self.SingUpButton.setObjectName("SingUpButton")
        self.verticalLayout.addWidget(self.SingUpButton)
        self.Back_button = QtWidgets.QCommandLinkButton(Login)
        self.Back_button.setObjectName("Back_button")
        self.verticalLayout.addWidget(self.Back_button)
        self.Error_textBrowser = QtWidgets.QTextBrowser(Login)
        self.Error_textBrowser.setObjectName("Error_textBrowser")
        self.verticalLayout.addWidget(self.Error_textBrowser)
        self.label = QtWidgets.QLabel(Login)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Login)
        self.LoginButton.clicked.connect(lambda :ui_home.setupUi(Login))

        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.UserName_libale.setText(_translate("Login", "UserName"))
        self.label_3.setText(_translate("Login", "Password"))
        self.LoginButton.setText(_translate("Login", "Login"))
        self.SingUpButton.setText(_translate("Login", "Sign up"))
        self.Back_button.setText(_translate("Login", "Back"))


def lunch_app():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())


ui = Ui_Login()
