from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfileMe(object):
    def setupUi(self, ProfileMe):
        ProfileMe.setObjectName("ProfileMe")
        ProfileMe.resize(600, 600)
        self.label = QtWidgets.QLabel(ProfileMe)
        self.label.setGeometry(QtCore.QRect(30, 30, 111, 20))
        self.label.setObjectName("label")
        self.Username_info = QtWidgets.QLabel(ProfileMe)
        self.Username_info.setGeometry(QtCore.QRect(60, 60, 121, 31))
        self.Username_info.setObjectName("Username_info")
        self.label_3 = QtWidgets.QLabel(ProfileMe)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 47, 13))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ProfileMe)
        self.label_4.setGeometry(QtCore.QRect(30, 100, 47, 13))
        self.label_4.setObjectName("label_4")
        self.FirstnameAndLastName = QtWidgets.QLabel(ProfileMe)
        self.FirstnameAndLastName.setGeometry(QtCore.QRect(60, 123, 121, 31))
        self.FirstnameAndLastName.setObjectName("FirstnameAndLastName")
        self.label_8 = QtWidgets.QLabel(ProfileMe)
        self.label_8.setGeometry(QtCore.QRect(360, 10, 47, 13))
        self.label_8.setObjectName("label_8")
        self.about = QtWidgets.QTextBrowser(ProfileMe)
        self.about.setGeometry(QtCore.QRect(360, 30, 211, 41))
        self.about.setObjectName("about")
        self.label_9 = QtWidgets.QLabel(ProfileMe)
        self.label_9.setGeometry(QtCore.QRect(460, 200, 91, 16))
        self.label_9.setObjectName("label_9")
        self.SupportLanguage = QtWidgets.QComboBox(ProfileMe)
        self.SupportLanguage.setGeometry(QtCore.QRect(510, 230, 69, 22))
        self.SupportLanguage.setObjectName("SupportLanguage")
        self.label_6 = QtWidgets.QLabel(ProfileMe)
        self.label_6.setGeometry(QtCore.QRect(360, 90, 81, 16))
        self.label_6.setObjectName("label_6")
        self.Introduction = QtWidgets.QTextBrowser(ProfileMe)
        self.Introduction.setGeometry(QtCore.QRect(360, 110, 211, 41))
        self.Introduction.setObjectName("Introduction")
        self.Skill = QtWidgets.QTextBrowser(ProfileMe)
        self.Skill.setGeometry(QtCore.QRect(30, 210, 411, 351))
        self.Skill.setObjectName("Skill")
        self.label_7 = QtWidgets.QLabel(ProfileMe)
        self.label_7.setGeometry(QtCore.QRect(40, 180, 47, 13))
        self.label_7.setObjectName("label_7")
        self.EditProfile = QtWidgets.QPushButton(ProfileMe)
        self.EditProfile.setGeometry(QtCore.QRect(450, 460, 75, 23))
        self.EditProfile.setObjectName("EditProfile")
        self.Back = QtWidgets.QCommandLinkButton(ProfileMe)
        self.Back.setGeometry(QtCore.QRect(450, 490, 185, 41))
        self.Back.setObjectName("Back")

        self.retranslateUi(ProfileMe)
        QtCore.QMetaObject.connectSlotsByName(ProfileMe)

    def retranslateUi(self, ProfileMe):
        _translate = QtCore.QCoreApplication.translate
        ProfileMe.setWindowTitle(_translate("ProfileMe", "Form"))
        self.label.setText(_translate("ProfileMe", "user name :"))
        self.Username_info.setText(_translate("ProfileMe", "user name "))
        self.label_4.setText(_translate("ProfileMe", "Name :"))
        self.FirstnameAndLastName.setText(_translate("ProfileMe", "Name + Last name"))
        self.label_8.setText(_translate("ProfileMe", "about :"))
        self.label_9.setText(_translate("ProfileMe", "support language:"))
        self.label_6.setText(_translate("ProfileMe", "Introduction:"))
        self.label_7.setText(_translate("ProfileMe", "skills:"))
        self.EditProfile.setText(_translate("ProfileMe", "Edit profile"))
        self.Back.setText(_translate("ProfileMe", "Back"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     ProfileMe = QtWidgets.QWidget()
#     ui = Ui_ProfileMe()
#     ui.setupUi(ProfileMe)
#     ProfileMe.show()
#     sys.exit(app.exec_())

ui = Ui_ProfileMe()
