from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(633, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Username = QtWidgets.QLabel(self.centralwidget)
        self.Username.setObjectName("Username")
        self.verticalLayout.addWidget(self.Username)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.Name = QtWidgets.QLabel(self.centralwidget)
        self.Name.setObjectName("Name")
        self.verticalLayout.addWidget(self.Name)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.Skill_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.Skill_textBrowser.setObjectName("Skill_textBrowser")
        self.verticalLayout.addWidget(self.Skill_textBrowser)
        self.EnrolSkill = QtWidgets.QPushButton(self.centralwidget)
        self.EnrolSkill.setObjectName("EnrolSkill")
        self.verticalLayout.addWidget(self.EnrolSkill)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.Intro_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.Intro_textBrowser.setObjectName("Intro_textBrowser")
        self.verticalLayout.addWidget(self.Intro_textBrowser)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.about_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.about_textBrowser.setObjectName("about_textBrowser")
        self.verticalLayout.addWidget(self.about_textBrowser)
        self.languages_fontComboBox = QtWidgets.QFontComboBox(self.centralwidget)
        self.languages_fontComboBox.setObjectName("languages_fontComboBox")
        self.verticalLayout.addWidget(self.languages_fontComboBox)
        self.connect_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.connect_checkBox.setObjectName("connect_checkBox")
        self.verticalLayout.addWidget(self.connect_checkBox)
        self.Back = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.Back.setObjectName("Back")
        self.verticalLayout.addWidget(self.Back)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "userName:"))
        self.Username.setText(_translate("MainWindow", "userName"))
        self.label_3.setText(_translate("MainWindow", "name:"))
        self.Name.setText(_translate("MainWindow", "first name + last name"))
        self.label_5.setText(_translate("MainWindow", "skill:"))
        self.EnrolSkill.setText(_translate("MainWindow", "Enrol Skill"))
        self.label_2.setText(_translate("MainWindow", "Intro :"))
        self.label_4.setText(_translate("MainWindow", "about:"))
        self.connect_checkBox.setText(_translate("MainWindow", "Connect"))
        self.Back.setText(_translate("MainWindow", "Back"))




# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
ui = Ui_MainWindow()